---
- name: ec2 launcher
  hosts: localhost
  tasks:
  - name: launching ec2
    ec2:
       instance_type: t2.micro
       key_name: ansibleweb
       image: ami-07c8bc5c1ce9598c3
       region: us-east-2
       group: default
       count: 3
       vpc_subnet_id: subnet-f28de4be
       wait: yes
       assign_public_ip: yes
       instance_tags:
               Name: hosts1000
 
