---
- hosts: localhost
  connection: local
  vars:
    region: us-east-2
  tasks:
    - name: Gather EC2 facts
      ec2_instance_info:
        region: "{{ region }}"
        filters:
          "tag:Name": "hosts1000"
      register: ec2
    - debug: var=ec2
    - name: Terminate EC2 Instance(s)
      ec2:
        instance_ids: '{{ item.instance_id }}'
        state: absent
        region: "{{ region }}"
      with_items: "{{ ec2.instances }}"
